version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - autentificación
  - clonación
  - Ether
  - multiprotocolo
  - Soft
  - Softether
  - softwares
  - tunelización
ignoreWords: []
import: []
